FROM public.ecr.aws/lambda/python:3.12

# Install production dependencies first (own layer — only rebuilds when deps change).
# requirements.txt is generated by deploy.ps1 via `uv export` before `docker build` runs.
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt && rm requirements.txt

# Copy application source into Lambda task root (already on PYTHONPATH in the base image)
COPY newsfloor/ ${LAMBDA_TASK_ROOT}/newsfloor/
COPY config.py ${LAMBDA_TASK_ROOT}/

CMD ["newsfloor.handler.lambda_handler"]
